website/views.py
from flask import Blueprint, render_template, redirect, url_for, jsonify, request
from flask_login import login_required, current_user

from . import db, role_required
from sqlalchemy.sql import text
from .models import Inmate, MessStatus, MealsLog, GuestLog, Expense
from datetime import datetime, date

views = Blueprint('views' ,__name__)

@views.route('/')
@login_required
def index():
    today = date.today().strftime("%Y-%m-%d")
    return redirect(url_for('views.get_by_date', date=today))

@views.route('/log_meals')
@login_required
def log_meals():
    today = date.today().strftime("%Y-%m-%d")
    return redirect(url_for('views.get_by_date', date=today))


@views.route('/manage_expense')
@login_required
@role_required('admin', 'secretary', 'steerer')
def manage_expense():
    expenses = db.session.execute(text(
            """SELECT e.*, u.user_name FROM expense e
            JOIN user u ON e.added_by = u.id
            ORDER BY e.bill_date DESC;"""
        )).fetchall()

    return render_template('manage_expense.html', expenses=expenses)


@views.route('/add_expense', methods=['POST'])
@login_required
@role_required('admin', 'secretary')
def add_expense():
    expense_name = request.form.get('expense_name')
    bill_date = request.form.get('bill_date')
    shop_name = request.form.get('shop_name')
    expense_type = request.form.get('expense_type')
    expense_category = request.form.get('expense_category')
    bill_amount = request.form.get('bill_amount')

    expense = Expense(
        note=expense_name,
        bill_date=bill_date,
        shop=shop_name,
        added_by=current_user.id,
        type=expense_type,
        category=expense_category,
        amount=bill_amount,
        last_edit=datetime.now()
    )

    db.session.add(expense)
    db.session.commit()

    return redirect(url_for('views.manage_expense'))


@views.route('/get_expense/<int:expense_id>', methods=['GET'])
@login_required
@role_required('admin', 'secretary')
def get_expense(expense_id):
    expense = Expense.query.get(expense_id)  # Retrieve the expense by ID
    result = {
        'id': expense.id,
        'note': expense.note,
        'bill_date': expense.bill_date.strftime('%Y-%m-%d'),
        'shop': expense.shop,
        'type': expense.type.name.lower(),
        'category': expense.category,
        'amount': expense.amount,
    }
    return jsonify(result)


@views.route('/update_expense/<int:expense_id>', methods=['POST'])
@login_required
def update_expense(expense_id):
    expense = Expense.query.get(expense_id)
    if expense:
        expense_name = request.form.get('expense_name')
        bill_date = request.form.get('bill_date')
        shop_name = request.form.get('shop_name')
        expense_type = request.form.get('expense_type')
        expense_category = request.form.get('expense_category')
        bill_amount = request.form.get('bill_amount')

        expense.note = expense_name
        expense.bill_date = datetime.strptime(bill_date, '%Y-%m-%d')
        expense.shop = shop_name
        expense.type = expense_type
        expense.category = expense_category
        expense.amount = bill_amount
        expense.last_edit = datetime.now()
        expense.edited_by = current_user.id

        db.session.commit()
        return redirect(url_for('views.manage_expense'))


@views.route('/delete_expense/<int:expense_id>', methods=['DELETE'])
def delete_expense(expense_id):
    try:
        expense = Expense.query.get(expense_id)  # Assuming SQLAlchemy ORM
        if not expense:
            return jsonify({"error": "Expense not found"}), 404

        db.session.delete(expense)
        db.session.commit()
        return jsonify({"message": "Expense deleted successfully"}), 200
    except Exception as e:
        db.session.rollback()
        return jsonify({"error": str(e)}), 500


@views.route('/get_by_date/<string:date>', methods=['GET'])
@login_required
def get_by_date(date):
    try:
        date_obj = datetime.strptime(date, '%Y-%m-%d').date()

        # Check and copy data if not available for the requested date
        if not is_data_available(date_obj):
            copy_data_from_previous_date(date_obj)

        # Fetch all inmate details and their statuses
        inmates = fetch_inmates_with_status(date_obj)
        return render_template('log_meals.html', inmates=inmates, selected_date=date)
    except Exception as e:
        db.session.rollback()
        return f"Error: {e}", 500


def is_data_available(date):
    """Check if data is available for the given date."""
    return db.session.execute(
        text("SELECT * FROM status_initialization_log WHERE date = :date"),
        {'date': date}
    ).scalar()


def copy_data_from_previous_date(date):
    """Copy data from the previous available date to the given date."""
    prev_date = get_previous_available_date(date)
    if prev_date:
        # Copy mess_status data
        copy_mess_status_data(date, prev_date)
        # Mark the new date as available
        mark_data_as_available(date)
        db.session.commit()


def get_previous_available_date(date):
    """Get the previous available date from the data_availability table."""
    return db.session.execute(
        text("SELECT date FROM status_initialization_log WHERE date < :date ORDER BY date DESC LIMIT 1"),
        {'date': date}
    ).scalar()


def copy_mess_status_data(new_date, prev_date):
    """Copy mess_status data from the previous date to the new date."""
    copy_query = """
        INSERT IGNORE INTO mess_status (inmate_id, update_date, in_status, last_edit, edited_by)
        SELECT inmate_id, :new_date, in_status, :last_edit, :edited_by
        FROM mess_status
        WHERE update_date = :prev_date;
    """
    db.session.execute(text(copy_query), {'new_date': new_date, 'prev_date': prev_date, 'last_edit': datetime.now(), 'edited_by': current_user.id})


def mark_data_as_available(date):
    """Mark the given date as available in the data_availability table."""
    db.session.execute(
        text("INSERT INTO status_initialization_log (date) VALUES (:date)"),
        {'date': date}
    )


def fetch_inmates_with_status(date):
    """Fetch all inmate details and their statuses for the given date."""
    query = """
        SELECT i.*, m.in_status, ml.breakfast, ml.lunch, ml.dinner, gl.guest_count, gl.sg_count
        FROM inmate i
        LEFT JOIN mess_status m ON i.inmate_id = m.inmate_id AND m.update_date = :date
        LEFT JOIN meals_log ml ON i.inmate_id = ml.inmate_id AND ml.update_date = :date
        LEFT JOIN guest_log gl ON i.inmate_id = gl.inmate_id AND gl.update_date = :date
        WHERE :date >= i.join_date ORDER BY i.mess_no;
    """
    return db.session.execute(text(query), params={'date': date})


@views.route('/get_inmate_details/<int:inmate_id>', methods=['GET'])
@login_required
def get_inmate_details(inmate_id):
    # Get date from the request
    date = request.args.get('date')

    if not date:
        return jsonify({'error': 'Date is required'}), 400

    query = """SELECT i.*, m.in_status, ml.breakfast, ml.lunch, ml.dinner, gl.guest_count, gl.sg_count
                FROM inmate i
                LEFT JOIN mess_status m ON i.inmate_id = m.inmate_id AND m.update_date = :date
                LEFT JOIN meals_log ml ON i.inmate_id = ml.inmate_id AND ml.update_date = :date
                LEFT JOIN guest_log gl ON i.inmate_id = gl.inmate_id AND gl.update_date = :date
                WHERE i.inmate_id = :inmate_id;"""

    inmate = db.session.execute(text(query), params={'date': date, 'inmate_id': inmate_id}).fetchone()

    # Return the inmate details as JSON response
    if inmate:
        return jsonify({
            'name': inmate.inmate_name,
            'department': inmate.department,
            'mess_number': inmate.mess_no,
            'is_ablc': inmate.is_ablc,
            'status': inmate.in_status,
            'breakfast': inmate.breakfast if inmate.breakfast is not None else 0,
            'lunch': inmate.lunch if inmate.lunch is not None else 0,
            'dinner': inmate.dinner if inmate.lunch is not None else 0,
            'guest_count': inmate.guest_count,
            'sg_count': inmate.sg_count,
            'is_bill_due': inmate.is_bill_due,
        })
    else:
        return jsonify({'error': 'Inmate not found'}), 404


@views.route('/update_inmate_status', methods=['POST'])
def update_inmate_status():
    try:
        data = request.get_json()  # Receive data as JSON
        inmate_id = data.get('inmate_id')
        date = data.get('date')
        status = data.get('status')
        breakfast = bool(data.get('breakfast'))
        lunch = bool(data.get('lunch'))
        dinner = bool(data.get('dinner'))
        guest_count = data.get('guest_count')
        sg_count = data.get('sg_count')
        print(data)

        # Update mess in status
        # Obtain mess in status from table
        mess_status = MessStatus.query.get({'inmate_id': inmate_id, 'update_date': date})
        if mess_status.in_status and (breakfast or lunch or dinner):
            print('Attempt to mess out inmate with meals logged.')
            return jsonify({'message': 'Attempt to mess out inmate with meals logged.'})

        if mess_status:
            # If mess in status is available in the table, update
            mess_status.in_status = status
            mess_status.last_edit = datetime.now()
            mess_status.edited_by = current_user.id
            db.session.commit()
        else:
            # Create new mess status
            mess_status = MessStatus(
                inmate_id=inmate_id,
                update_date=date,
                in_status=status,
                last_edit=datetime.now(),
                edited_by=current_user.id
            )
            db.session.add(mess_status)
            db.session.commit()

        meals_log = MealsLog.query.get({'inmate_id': inmate_id, 'update_date': date})
        if meals_log:

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Title{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <!-- <link rel="stylesheet" href="../static/css/base.css"> -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css')}}">
    {% block styles %}
    {% endblock %}
</head>
<body>
    <!-- Navbar -->
    <nav>
        <a class="navbar-brand" href="#">MH Mess</a>
        <span class="vertical-separator"></span>
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link  {% if request.endpoint == 'views.get_by_date' %}link-active{% endif %}" href="{{ url_for('views.log_meals') }}">Log Meals</a></li>

            {% if current_user.role in ['admin', 'secretary'] %}
                <li class="nav-item"><a class="nav-link  {% if request.endpoint in ['inmates.manage_inmates', 'inmates.inmate_view'] %}link-active{% endif %}" href="{{ url_for('inmates.manage_inmates') }}">Manage Inmates</a></li>
            {% endif %}

            <li class="nav-item"><a class="nav-link  {% if request.endpoint in ['summaries.summery', 'summaries.daily_summery'] %}link-active{% endif %}" href="{{ url_for('summaries.summery') }}">View Summary</a></li>

            {% if current_user.role in ['admin', 'secretary', 'steerer', 'manager'] %}
                <li class="nav-item"><a class="nav-link  {% if request.endpoint == 'views.manage_expense' %}link-active{% endif %}" href="{{ url_for('views.manage_expense') }}">Manage Expenses</a></li>
<!--                <li class="nav-item"><a class="nav-link  {% if request.endpoint == 'summaries.bills' %}link-active{% endif %}" href="{{ url_for('summaries.bills') }}">Bills</a></li> -->
            {% endif %}

            {% if current_user.role in ['admin', 'secretary'] %}
                <li class="nav-item"><a class="nav-link  {% if request.endpoint == 'auth.manage_users' %}link-active{% endif %}" href="{{ url_for('auth.manage_users') }}">Manage Users</a></li>
            {% endif %}
        </ul>

        <img src="{{ url_for('static', filename=current_user.profile_pic) }}" alt="profile-picture" class="profile-pic" onclick="toggleProfileMenu()">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="material-symbols-outlined">menu</span>
        </button>
    </nav>

    <div id="profile-menu" class="account">
        <div class="row1">
            <img src="{{ url_for('static', filename=current_user.profile_pic) }}" alt="profile-picture">
            <div class="col">
                <span class="user-name">{{ current_user.user_name }}</span>
                <span class="user-role">{{ current_user.role.capitalize() }}</span>
            </div>
        </div>
        <hr>
        <a href="/logout" class="logout" onclick="return logout(event);">
            <span class="material-symbols-outlined">logout</span>
            Logout
        </a>
    </div>

    <!-- Content Section -->
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <script src="{{ url_for('static', filename='js/base.js')}}"></script>
    <script>
        function toggleProfileMenu() {
            const menu = document.getElementById('profile-menu');
            menu.classList.toggle('show');
        }

        // Close the menu when clicking outside
        document.addEventListener('click', function(event) {
            const profilePic = document.querySelector('.profile-pic');
            const menu = document.getElementById('profile-menu');

            if (!menu.contains(event.target) && !profilePic.contains(event.target)) {
                menu.classList.remove('show');
            }
        });

        function logout(event) {
            const menu = document.getElementById('profile-menu');
            menu.classList.remove('show');

            const consent = confirm('Are you sure you want to logout?');

            if (consent == false) {
                event.preventDefault();
                return false;
            }

            return true;
        }
    </script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

website/templates/bills.html
{% extends "base.html" %}

{% block title %}Summary{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/summery.css') }}">
{% endblock %}

{% block content %}
<div class="container">

    <div class="popup" id="dailyPopup">
        <span class="material-symbols-outlined close-btn" id="closePopup" onclick="closePopup('dailyPopup')">close</span>
        <form action="/daily_summery" method="get">
            <h2>Summery by Date</h2>
            <label for="date">Choose Date: </label>
            <input type="date" name="date" id="date" class="form-control">

            <input class="btn" type="submit" value="Get Summery">
        </form>
    </div>

    <div class="popup" id="monthlyPopup">
        <span class="material-symbols-outlined close-btn" id="closePopup" onclick="closePopup('monthlyPopup')">close</span>
        <form action="/monthly_summery" method="get">
            <h2>Summery by Month</h2>
            <label for="month">Choose Month: </label>
            <select name="month" id="month" class="form-control">
                <option value="January">January</option>
                <option value="February">February</option>
                <option value="March">March</option>
                <option value="April">April</option>
                <option value="May">May</option>
                <option value="June">June</option>
                <option value="July">July</option>
                <option value="August">August</option>
                <option value="September">September</option>
                <option value="October">October</option>
                <option value="November">November</option>
                <option value="December">December</option>
            </select>
        
            <label for="year" style="margin-top: 10px;">Choose Year: </label>
            <select name="year" id="year" class="form-control">
                <option value="2025">2025</option>
            </select>

            <input class="btn" type="submit" value="Get Summery" style="margin-top: 15px;">
        </form>
    </div>

    <h1>View Bills</h1>

    <form action="/choose_month" id="setMonth" style="flex-direction: row;" method="GET">
        <select name="year" id="year" class="form-control" required>
            <option disabled selected>Select Year</option>
            <option value="2025">2025</option>
        </select>
        <select name="month" id="month" class="form-control" required>
            <option disabled selected>Select Month</option>
            <option value="January">January</option>
            <option value="February">February</option>
            <option value="March">March</option>
            <option value="April">April</option>
            <option value="May">May</option>
            <option value="June">June</option>
            <option value="July">July</option>
            <option value="August">August</option>
            <option value="September">September</option>
            <option value="October">October</option>
            <option value="November">November</option>
            <option value="December">December</option>
        </select>
        <input type="submit" class="btn" value="Get Details" style="margin-top: 0;">
    </form>

    {% if monthly_data %}
    <section class="monthly-summery" id="monthly-summery">
        <h1>Monthly Bill of {{ monthly_data['month'] }}, {{ monthly_data['year'] }}</h1>

        {% if monthly_data %}
        <table style="margin: 20px 0;">
            <tr>
                <th>Category</th>
                <th>Amount</th>
            </tr>
            <tr>
                <td>Net Purchase</td>
                <td>{{ monthly_data['net_purchase'] }}</td>
            </tr>
            <tr>
                <td>Net Fixed</td>
                <td>{{ monthly_data['net_fixed'] }}</td>
            </tr>
            <tr>
                <td>Total Guest Count</td>
                <td>{{ monthly_data['total_guest_count'] }}</td>
            </tr>
            <tr>
                <td>Total SG Count</td>
                <td>{{ monthly_data['total_sg_count'] }}</td>
            </tr>
            <tr>
                <td>Total Guest Charges</td>
                <td>{{ monthly_data['total_guest_charges'] }}</td>
            </tr>
            <tr>
                <td>Number of Inmates</td>
                <td>{{ monthly_data['inmate_count'] }}</td>
            </tr>
            <tr>
                <td>Number of Joins</td>
                <td>{{ monthly_data['join_count'] }}</td>
            </tr>
            <tr>
                <td>Fixed Charges per Inmate</td>
                <td>{{ monthly_data['fixed_per_head'] }}</td>
            </tr>
            <tr>
                <td>Daily Expense per Inmate</td>
                <td>{{ monthly_data['expense_per_head'] }}</td>
            </tr>
        </table>
        {% endif %}

        <div class="overflow-x">
            <table id="monthly">
                <tr>
                    <th>Mess No.</th>
                    <th>Inmate Name</th>
                    <th>Department</th>
                    <th>ABLC</th>
                    <th>Join Count</th>
                    <th>Guest Count</th>
                    <th>SG Count</th>
                    <th>Join Amount</th>
                    <th>Guest Charges</th>
                    <th>Net Bill Amount</th>
                </tr>

                {% for inmate in monthly_data['inmate_summery'] %}
                <tr>
                    <td>{{ inmate['mess_no'] }}</td>
                    <td>{{ inmate['inmate_name'] }}</td>
                    <td>{{ inmate['department'] }}</td>
                    <td>{{ "ABLC" if inmate['is_ablc'] else "" }}</td>
                    <td>{{ inmate['join_count'] }}</td>
                    <td>{{ inmate['guest_count'] }}</td>
                    <td>{{ inmate['sg_count'] }}</td>
                    <td>{{ inmate['join_amount'] }}</td>
                    <td>{{ inmate['guest_amount'] }}</td>
                    <td>{{ inmate['bill_amount'] }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </section>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script>
    const today = new Date().toISOString().split('T')[0];
    document.getElementById('date').value = today;

    function showPopup(id) {
        const popup = document.getElementById(id);
        popup.style.display = 'block';
    }

    function closePopup(id) {
        const popup = document.getElementById(id);
        popup.style.display = 'none';
    }
</script>
{% endblock %}

website/templates/inmate_dash.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MH Mess | Inmate Dashboard</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/view_inmates.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/table.css') }}">

<style>
    .card {
        width: 100%;
        padding: 10px;
        background-color: #f1f1f1;
        border-radius: 10px;
        margin: 20px 0;
        display: flex;
        justify-content: space-between;
    }

    .card-col {
        display: flex;
        flex-direction: column;
        width: 100%;
        gap: 15px;
        position: relative;
    }

    .card-group {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        justify-content: center;
    }

    .label {
        font-size: 0.9rem;
        font-weight: 600;
        color: #424242;
    }

    .value {
        font-size: 1.2rem;
        color: rgb(104, 40, 6);
    }

    #person {
        width: 150px;
        height: 180px;
        object-fit: cover;
        border-radius: 10px;
        position: absolute;
        right: 0;
    }

    @media (max-width: 800px) {
        .card {
            flex-direction: column;
            gap: 15px;
        }

        #person {
            position: relative;
            align-self: center;
        }
    }
</style>
</head>
<body>
    <!-- Navbar -->
    <nav>
        <a class="navbar-brand" href="#">MH Mess</a>
        <span class="vertical-separator"></span>
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link link-active" href="#">Inmate Dashboard</a></li>
        </ul>
    </nav>

    <!-- Content Section -->
    <main>
        <div class="container">
            <h1>Inmate Details</h1>
        
            <div class="card">
                <div class="card-col">
                    <div class="card-group">
                        <span class="label">Inmate ID</span>
                        <span class="value">{{ inmate['inmate_id'] }}</span>
                    </div>
        
                    <div class="card-group">
                        <span class="label">Mess Number</span>
                        <span class="value">{{ inmate['mess_no'] }}</span>
                    </div>
        
                    <div class="card-group">
                        <span class="label">Name</span>
                        <span class="value">{{ inmate['inmate_name'] }}</span>
                    </div>
                </div>
        
                <div class="card-col">
                    <div class="card-group">
                        <span class="label">Department</span>
                        <span class="value">{{ inmate['department'] }}</span>
                    </div>
        
                    <div class="card-group">
                        <span class="label">ABLC</span>
                        <span class="value">{{ inmate['is_ablc'] }}</span>
                    </div>
        
                    <div class="card-group">
                        <span class="label">Bill Due</span>
                        {% if inmate['is_bill_due'] > 0 %}
                        <span class="value">{{ inmate['is_bill_due'] }} Bills Due</span>
                        {% else %}
                        <span class="value">No Due</span>
                        {% endif %}
                    </div>
                </div>
        
                <div class="card-col">
                    <img src="{{ url_for('static', filename='images/inmates/' + inmate['image']) }}" id="person" alt="person" class="person">
                </div>
            </div>
        
            {% if days_info %}
            <h2>Available Join Data</h2>
            <div class="overflow-x">
                <table id="join-data-table">
                    <thead>
                        <tr>
                            <th>Sl No.</th>
                            <th>Month</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for record in days_info %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>{{ record[0] }}/{{ record[1] }}</td>
                            <td><a onclick="showDatesPopup('{{ record[0] }}', '{{ record[1] }}');">View</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
        
            <h2>Available Bills</h2>
            <div class="overflow-x">
                <table id="bills-table">
                    <tr>
                        <th>Sl No.</th>
                        <th>Bill Month</th>
                        <th>Bill Date</th>
                        <th>Amount</th>
                        <th>Status</th>
                        <th>Paid Date</th>
                        <th>Reference ID</th>
                    </tr>
                    {% for bill in bills %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ bill['month']}}/{{bill['year']}}</td>
                        <td>{{ bill['generated_date'] }}</td>
                        <td>{{ bill['amount'] }}</td>
                        <td>{{ bill['status'] }}</td>
                        <td>{{ bill['paid_date'] }}</td>
                        <td>{{ bill['reference_id'] }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        
        <div class="backdrop" id="backdrop"></div>
        
        <div class="popup" id="popup">
            <h1>Dates</h1>
            <span class="material-symbols-outlined close-btn" id="closePopup" onclick="closePopup('popup')">close</span>
            
            <div class="table-container">
                <div class="table-wrapper">
                    <table id="joins-table">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Mess In/Out</th>
                                <th>Guest</th>
                                <th>SG</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Rows will be dynamically inserted here -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        
        <div class="popup" id="paidPopup">
            <h1>Save Bill as Paid</h1>
            <span class="material-symbols-outlined close-btn" id="closePopup" onclick="closePopup('paidPopup')">close</span>
            <form>
                <div class="input-item">
                    <label for="paid_date" class="form-label">Paid Date</label>
                    <input type="date" class="form-control" name="paid_date" id="paid_date">
                </div>
        
                <div class="input-item">
                    <label for="reference_id" class="form-label">Reference ID</label>
                    <input type="text" class="form-control" name="reference_id" id="reference_id" placeholder="Enter Reference ID">
                </div>
        
                <input type="submit" class="btn btn-long-m" value="Submit">
            </form>
        </div>
    </main>

    <script>
        const popup = document.getElementById('popup');
        const backdrop = document.getElementById('backdrop');
        let inmate = null;
    
        function showDatesPopup(month, year) {
            const inmateId = "{{ inmate['inmate_id'] }}";
            popup.style.display = 'block';
    
            // Fetch data from the Flask backend
            fetch(`/show_joins?inmateId=${inmateId}&month=${month}&year=${year}`)
                .then(response => response.json()) // Parse the JSON response
                .then(data => {
                    console.log('Inmate: ' + data)
                    // Get the table body
                    const tableBody = document.querySelector('#joins-table tbody');
                    tableBody.innerHTML = ''; // Clear any existing rows
    
                    // Loop through the data and add rows to the table
                    data.forEach(row => {
                        const tr = document.createElement('tr');
    
                        row.guest_count = row.guest_count == null || row.guest_count == 0 ? '' : row.guest_count;
                        row.sg_count = row.sg_count == null || row.sg_count == 0 ? '' : row.sg_count;
    
                        tr.innerHTML = `
                            <td style="width: auto;">${row.update_date}</td>
                            <td style="width: auto;">${row.in_status}</td>
                            <td style="width: auto;">${row.guest_count}</td>
                            <td style="width: auto;">${row.sg_count}</td>
                        `;
                        tableBody.appendChild(tr);
                    });
                })
                .catch(error => {
                    console.error('Error fetching data:', error);
                });
        }
    
        function closePopup(popup) {
            backdrop.style.display = 'none';
            document.getElementById(popup).style.display = 'none';
        }
    </script>
</body>
</html>